services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  restaurant-service:
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  delivery-service:
    build:
      context: ./delivery-service
    container_name: delivery-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
