[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run prisma:generate && npm run build && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[build.env]
NODE_ENV = "production"